# Generated by Django 3.2.6 on 2021-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=11)),
                ('country_name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=200)),
                ('time_zone', models.CharField(max_length=250)),
                ('latitude', models.FloatField(max_length=200)),
                ('longitude', models.FloatField(max_length=200)),
            ],
        ),
    ]
