# Generated by Django 3.2.6 on 2021-09-03 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_auto_20210903_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='video_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='ytd_request_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
