# Generated by Django 3.2.6 on 2021-09-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0003_auto_20210903_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='video_thumb_img',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
