# Generated by Django 3.2.6 on 2021-09-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0004_visitor_video_thumb_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country_code',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='latitude',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='longitude',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_zone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
