# Generated by Django 3.2.6 on 2021-09-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0005_auto_20210903_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='city',
        ),
    ]
