# Generated by Django 3.2.6 on 2021-08-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210813_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
