# Generated by Django 3.2.6 on 2021-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_needjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needjob',
            name='age',
            field=models.IntegerField(),
        ),
    ]
